---
- name: PREVENT RUN WITHOUT TAGS
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
    - name: PREVENT RUN WITHOUT TAGS
      fail: msg="You must run this playbook with tags! [present|absent]"

- name: PROVISION GCP INFRASTRUCTURE USING TERRAFORM
  hosts: localhost
  gather_facts: no
  connection: local
  tags: present

  tasks:
    - name: PROVISION GCP COMPUTE USING TERRAFORM
      terraform:
        project_path: "{{ playbook_dir }}/gcp"
        state: present  
        force_init: yes
        variables: 
          gcp_id: "{{ gcp_project_id }}"
          gcp_credential: "{{ gcp_cred_path }}"
        backend_config:
          access_key: "{{ aws_access_key }}"
          secret_key: "{{ aws_secret_key }}"
          bucket: "{{ aws_bucket }}"
          key: "{{aws_key}}"
          region: "{{ aws_region }}"
      register: output

    - debug:
        msg: "{{ output }}"
      
    - meta: refresh_inventory

    - debug:
        var: groups


- name: TEARDOWN GCP INFRASTRUCTURE USING TERRAFORM
  hosts: localhost
  gather_facts: no
  connection: local
  tags: absent

  tasks:
    - name: TEARDOWN GCP COMPUTE USING TERRAFORM
      terraform:
        project_path: "{{ playbook_dir }}/gcp"
        state: absent
        force_init: yes
        variables:
          gcp_id: "{{ gcp_project_id }}"
          gcp_credential: "{{ gcp_cred_path }}"
        backend_config:
          access_key: "{{ aws_access_key }}"
          secret_key: "{{ aws_secret_key }}"
          bucket: "{{ aws_bucket }}"
          key: "{{aws_key}}"
          region: "{{ aws_region }}"
      register: output

    - debug:
        msg: "{{ output }}"