---
- name: PREVENT RUN WITHOUT TAGS
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
    - name: PREVENT RUN WITHOUT TAGS
      fail: msg="You must run this playbook with tags! [present|absent]"

- name: PROVISION AWS INFRASTRUCTURE USING TERRAFORM
  hosts: localhost
  gather_facts: no
  connection: local
  tags: present

  tasks:
    - name: PROVISION AWS INFRASTRUCTURE USING TERRAFORM
      terraform:
        project_path: "{{ playbook_dir }}/aws"
        state: present
        force_init: yes
        variables:
          aws_access_key: "{{ aws_access_key }}"
          aws_secret_key: "{{ aws_secret_key }}"
        backend_config:
          access_key: "{{ aws_access_key }}"
          secret_key: "{{ aws_secret_key }}"
          bucket: "{{ aws_bucket }}"
          key: "{{aws_key}}"
          region: "{{ aws_region }}"
      register: output

    - debug:
        msg: "{{ output }}"

- name: TEARDOWN AWS INFRASTRUCTURE USING TERRAFORM
  hosts: localhost
  gather_facts: no
  connection: local
  tags: absent

  tasks:
    - name: TEARDOWN AWS INFRASTRUCTURE USING TERRAFORM
      terraform:
        project_path: "{{ playbook_dir }}/aws"
        state: absent
        force_init: yes
        variables:
          aws_access_key: "{{ aws_access_key }}"
          aws_secret_key: "{{ aws_secret_key }}"
        backend_config:
          access_key: "{{ aws_access_key }}"
          secret_key: "{{ aws_secret_key }}"
          bucket: "{{ aws_bucket }}"
          key: "{{aws_key}}"
          region: "{{ aws_region }}"
      register: output

    - debug:
        msg: "{{ output }}"